#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 12.09.2021 19:50
# Generated By: Janis
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$ziel = New-Object System.Windows.Forms.Label
$pfad2loeschen = New-Object System.Windows.Forms.Button
$pfad2suche = New-Object System.Windows.Forms.Button
$pfad2 = New-Object System.Windows.Forms.TextBox
$start = New-Object System.Windows.Forms.Button
$listBox2 = New-Object System.Windows.Forms.ListBox
$passeingabe = New-Object System.Windows.Forms.TextBox
$pass = New-Object System.Windows.Forms.CheckBox
$zip = New-Object System.Windows.Forms.CheckBox
$pfad1loeschen = New-Object System.Windows.Forms.Button
$pfad1suche = New-Object System.Windows.Forms.Button
$label4 = New-Object System.Windows.Forms.Label
$pfad1 = New-Object System.Windows.Forms.TextBox
$drives = New-Object System.Windows.Forms.ListBox
$bilder = New-Object System.Windows.Forms.CheckBox
$musik = New-Object System.Windows.Forms.CheckBox
$videos = New-Object System.Windows.Forms.CheckBox
$dokumente = New-Object System.Windows.Forms.CheckBox
$downloads = New-Object System.Windows.Forms.CheckBox
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$desktop = New-Object System.Windows.Forms.CheckBox
$openFileDialog1 = New-Object System.Windows.Forms.OpenFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$pfad2loeschen_OnClick= 
{
#TODO: Place custom script here

}

$pfad1suche_OnClick= 
{
#TODO: Place custom script here

}

$start_OnClick= 
{
#TODO: Place custom script here

}

$handler_checkBox7_CheckedChanged= 
{
#TODO: Place custom script here

}

$pfad1loeschen_OnClick= 
{
#TODO: Place custom script here

}

$handler_checkBox3_CheckedChanged= 
{
#TODO: Place custom script here

}

$pfad2suche_OnClick= 
{
#TODO: Place custom script here

}

$handler_textBox2_TextChanged= 
{
#TODO: Place custom script here

}

$handler_form1_Load= 
{
#TODO: Place custom script here

}

$handler_checkBox5_CheckedChanged= 
{
#TODO: Place custom script here

}

$handler_openFileDialog1_FileOk= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackColor = [System.Drawing.Color]::FromArgb(255,0,120,215)
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 410
$System_Drawing_Size.Width = 849
$form1.ClientSize = $System_Drawing_Size
$form1.Cursor = [System.Windows.Forms.Cursors]::Arrow
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Font = New-Object System.Drawing.Font("Calibri",8.25,0,3,0)
$form1.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$form1.Name = "form1"
$form1.Text = "Backup"
$form1.add_Load($handler_form1_Load)

$ziel.DataBindings.DefaultDataSourceUpdateMode = 0
$ziel.Font = New-Object System.Drawing.Font("Calibri",20.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 609
$System_Drawing_Point.Y = 26
$ziel.Location = $System_Drawing_Point
$ziel.Name = "ziel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 37
$System_Drawing_Size.Width = 76
$ziel.Size = $System_Drawing_Size
$ziel.TabIndex = 18
$ziel.Text = "Ziel:"

$form1.Controls.Add($ziel)


$pfad2loeschen.DataBindings.DefaultDataSourceUpdateMode = 0
$pfad2loeschen.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 322
$System_Drawing_Point.Y = 212
$pfad2loeschen.Location = $System_Drawing_Point
$pfad2loeschen.Name = "pfad2loeschen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 25
$pfad2loeschen.Size = $System_Drawing_Size
$pfad2loeschen.TabIndex = 23
$pfad2loeschen.Text = "X"
$pfad2loeschen.UseVisualStyleBackColor = $True
$pfad2loeschen.add_Click($pfad2loeschen_OnClick)

$form1.Controls.Add($pfad2loeschen)


$pfad2suche.DataBindings.DefaultDataSourceUpdateMode = 0
$pfad2suche.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 292
$System_Drawing_Point.Y = 212
$pfad2suche.Location = $System_Drawing_Point
$pfad2suche.Name = "pfad2suche"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 24
$pfad2suche.Size = $System_Drawing_Size
$pfad2suche.TabIndex = 22
$pfad2suche.Text = "..."
$pfad2suche.UseVisualStyleBackColor = $True
$pfad2suche.add_Click($pfad2suche_OnClick)

$form1.Controls.Add($pfad2suche)

$pfad2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 213
$pfad2.Location = $System_Drawing_Point
$pfad2.Name = "pfad2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 242
$pfad2.Size = $System_Drawing_Size
$pfad2.TabIndex = 21

$form1.Controls.Add($pfad2)


$start.DataBindings.DefaultDataSourceUpdateMode = 0
$start.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$start.ForeColor = [System.Drawing.Color]::FromArgb(255,0,128,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 351
$start.Location = $System_Drawing_Point
$start.Name = "start"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 32
$System_Drawing_Size.Width = 823
$start.Size = $System_Drawing_Size
$start.TabIndex = 20
$start.Text = "Start"
$start.UseVisualStyleBackColor = $True
$start.add_Click($start_OnClick)

$form1.Controls.Add($start)

$listBox2.DataBindings.DefaultDataSourceUpdateMode = 0
$listBox2.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 249
$listBox2.Location = $System_Drawing_Point
$listBox2.Name = "listBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 95
$System_Drawing_Size.Width = 824
$listBox2.Size = $System_Drawing_Size
$listBox2.TabIndex = 19

$form1.Controls.Add($listBox2)

$passeingabe.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 545
$System_Drawing_Point.Y = 213
$passeingabe.Location = $System_Drawing_Point
$passeingabe.Name = "passeingabe"
$passeingabe.PasswordChar = '?'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 193
$passeingabe.Size = $System_Drawing_Size
$passeingabe.TabIndex = 17
$passeingabe.add_TextChanged($handler_textBox2_TextChanged)

$form1.Controls.Add($passeingabe)


$pass.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 545
$System_Drawing_Point.Y = 183
$pass.Location = $System_Drawing_Point
$pass.Name = "pass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 219
$pass.Size = $System_Drawing_Size
$pass.TabIndex = 16
$pass.Text = "Zip Archiv mit Passwort verschlüsseln"
$pass.UseVisualStyleBackColor = $True

$form1.Controls.Add($pass)


$zip.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 545
$System_Drawing_Point.Y = 158
$zip.Location = $System_Drawing_Point
$zip.Name = "zip"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 193
$zip.Size = $System_Drawing_Size
$zip.TabIndex = 15
$zip.Text = "Dateien als Zip Archiv speichern"
$zip.UseVisualStyleBackColor = $True
$zip.add_CheckedChanged($handler_checkBox7_CheckedChanged)

$form1.Controls.Add($zip)


$pfad1loeschen.DataBindings.DefaultDataSourceUpdateMode = 0
$pfad1loeschen.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 322
$System_Drawing_Point.Y = 184
$pfad1loeschen.Location = $System_Drawing_Point
$pfad1loeschen.Name = "pfad1loeschen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 25
$pfad1loeschen.Size = $System_Drawing_Size
$pfad1loeschen.TabIndex = 14
$pfad1loeschen.Text = "X"
$pfad1loeschen.UseVisualStyleBackColor = $True
$pfad1loeschen.add_Click($pfad1loeschen_OnClick)

$form1.Controls.Add($pfad1loeschen)


$pfad1suche.DataBindings.DefaultDataSourceUpdateMode = 0
$pfad1suche.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 292
$System_Drawing_Point.Y = 184
$pfad1suche.Location = $System_Drawing_Point
$pfad1suche.Name = "pfad1suche"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 24
$pfad1suche.Size = $System_Drawing_Size
$pfad1suche.TabIndex = 13
$pfad1suche.Text = "..."
$pfad1suche.UseVisualStyleBackColor = $True
$pfad1suche.add_Click($pfad1suche_OnClick)

$form1.Controls.Add($pfad1suche)

$label4.DataBindings.DefaultDataSourceUpdateMode = 0
$label4.Font = New-Object System.Drawing.Font("Calibri",9.75,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 161
$label4.Location = $System_Drawing_Point
$label4.Name = "label4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 197
$label4.Size = $System_Drawing_Size
$label4.TabIndex = 12
$label4.Text = "Weitere Pfade zum sichern:"

$form1.Controls.Add($label4)

$pfad1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 186
$pfad1.Location = $System_Drawing_Point
$pfad1.Name = "pfad1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 242
$pfad1.Size = $System_Drawing_Size
$pfad1.TabIndex = 11

$form1.Controls.Add($pfad1)

$drives.DataBindings.DefaultDataSourceUpdateMode = 0
$drives.FormattingEnabled = $True
$drives.Items.Add("Bitte warten...")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 438
$System_Drawing_Point.Y = 73
$drives.Location = $System_Drawing_Point
$drives.Name = "drives"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 82
$System_Drawing_Size.Width = 398
$drives.Size = $System_Drawing_Size
$drives.TabIndex = 10

$form1.Controls.Add($drives)

$drives.Items.Clear()
$drivevar = (Get-PSDrive -PSProvider FileSystem).Root
for ($i=0; $i -lt $drivevar.length; $i++){
    $drives.Items.Add($drivevar[$i])|Out-Null }

$bilder.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 231
$System_Drawing_Point.Y = 130
$bilder.Location = $System_Drawing_Point
$bilder.Name = "bilder"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$bilder.Size = $System_Drawing_Size
$bilder.TabIndex = 7
$bilder.Text = "Bilder"
$bilder.UseVisualStyleBackColor = $True

$form1.Controls.Add($bilder)


$musik.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 130
$musik.Location = $System_Drawing_Point
$musik.Name = "musik"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$musik.Size = $System_Drawing_Size
$musik.TabIndex = 6
$musik.Text = "Musik"
$musik.UseVisualStyleBackColor = $True
$musik.add_CheckedChanged($handler_checkBox5_CheckedChanged)

$form1.Controls.Add($musik)


$videos.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 231
$System_Drawing_Point.Y = 100
$videos.Location = $System_Drawing_Point
$videos.Name = "videos"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$videos.Size = $System_Drawing_Size
$videos.TabIndex = 5
$videos.Text = "Videos"
$videos.UseVisualStyleBackColor = $True

$form1.Controls.Add($videos)


$dokumente.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 100
$dokumente.Location = $System_Drawing_Point
$dokumente.Name = "dokumente"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$dokumente.Size = $System_Drawing_Size
$dokumente.TabIndex = 4
$dokumente.Text = "Dokumente"
$dokumente.UseVisualStyleBackColor = $True
$dokumente.add_CheckedChanged($handler_checkBox3_CheckedChanged)

$form1.Controls.Add($dokumente)


$downloads.DataBindings.DefaultDataSourceUpdateMode = 0
$downloads.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 231
$System_Drawing_Point.Y = 73
$downloads.Location = $System_Drawing_Point
$downloads.Name = "downloads"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$downloads.Size = $System_Drawing_Size
$downloads.TabIndex = 3
$downloads.Text = "Downloads"
$downloads.UseVisualStyleBackColor = $True

$form1.Controls.Add($downloads)

$label2.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 410
$System_Drawing_Point.Y = -2
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 264
$System_Drawing_Size.Width = 10
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 2

$form1.Controls.Add($label2)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0
$label1.Font = New-Object System.Drawing.Font("Calibri",20.25,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 125
$System_Drawing_Point.Y = 26
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 37
$System_Drawing_Size.Width = 180
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 1
$label1.Text = "Quelle:"

$form1.Controls.Add($label1)


$desktop.DataBindings.DefaultDataSourceUpdateMode = 0
$desktop.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 66
$desktop.Location = $System_Drawing_Point
$desktop.Name = "desktop"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 39
$System_Drawing_Size.Width = 118
$desktop.Size = $System_Drawing_Size
$desktop.TabIndex = 0
$desktop.Text = "Desktop"
$desktop.UseVisualStyleBackColor = $True

$form1.Controls.Add($desktop)

$openFileDialog1.FileName = "openFileDialog1"
$openFileDialog1.ShowHelp = $True
$openFileDialog1.add_FileOk($handler_openFileDialog1_FileOk)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm

